-- ============================================================
-- AI Market Intelligence Platform - PostgreSQL Schema
-- Converted from the provided DBML
-- ============================================================

BEGIN;

-- ============================================================
-- DROP EXISTING TABLES
-- Development reset: removes tables and dependent objects/data.
-- ============================================================

DROP TABLE IF EXISTS signals CASCADE;
DROP TABLE IF EXISTS analysis_inputs CASCADE;
DROP TABLE IF EXISTS analysis_sources CASCADE;
DROP TABLE IF EXISTS analyses CASCADE;
DROP TABLE IF EXISTS classification_assets CASCADE;
DROP TABLE IF EXISTS source_classifications CASCADE;
DROP TABLE IF EXISTS onchain_data CASCADE;
DROP TABLE IF EXISTS reports CASCADE;
DROP TABLE IF EXISTS tweets CASCADE;
DROP TABLE IF EXISTS news_articles CASCADE;
DROP TABLE IF EXISTS data_sources CASCADE;
DROP TABLE IF EXISTS market_data CASCADE;
DROP TABLE IF EXISTS bot_parameters CASCADE;
DROP TABLE IF EXISTS risk_bots CASCADE;
DROP TABLE IF EXISTS arbitrage_bots CASCADE;
DROP TABLE IF EXISTS sentiment_bots CASCADE;
DROP TABLE IF EXISTS trading_bots CASCADE;
DROP TABLE IF EXISTS bots CASCADE;
DROP TABLE IF EXISTS portfolio_assets CASCADE;
DROP TABLE IF EXISTS portfolios CASCADE;
DROP TABLE IF EXISTS favorites CASCADE;
DROP TABLE IF EXISTS commodities CASCADE;
DROP TABLE IF EXISTS forex CASCADE;
DROP TABLE IF EXISTS crypto CASCADE;
DROP TABLE IF EXISTS stocks CASCADE;
DROP TABLE IF EXISTS assets CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- ============================================================
-- USERS
-- ============================================================
CREATE TABLE users (
    usr_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usr_username VARCHAR UNIQUE NOT NULL,
    usr_email VARCHAR UNIQUE NOT NULL,
    usr_password_hash VARCHAR NOT NULL,
    usr_is_active BOOLEAN DEFAULT TRUE,
    usr_created_at TIMESTAMP DEFAULT NOW()
);

-- ============================================================
-- ASSETS
-- ============================================================
CREATE TABLE assets (
    ast_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ast_symbol VARCHAR UNIQUE NOT NULL,
    ast_name VARCHAR NOT NULL,
    ast_type VARCHAR NOT NULL,
    ast_is_active BOOLEAN DEFAULT TRUE,
    ast_created_at TIMESTAMP DEFAULT NOW()
);

-- ============================================================
-- STOCKS
-- ============================================================
CREATE TABLE stocks (
    sto_ast_id INTEGER PRIMARY KEY,
    sto_exchange VARCHAR NOT NULL,
    sto_sector VARCHAR,
    sto_industry VARCHAR,
    CONSTRAINT fk_stocks_asset
        FOREIGN KEY (sto_ast_id) REFERENCES assets(ast_id)
);

-- ============================================================
-- CRYPTO
-- ============================================================
CREATE TABLE crypto (
    cry_ast_id INTEGER PRIMARY KEY,
    cry_blockchain VARCHAR,
    cry_contract_address VARCHAR,
    CONSTRAINT fk_crypto_asset
        FOREIGN KEY (cry_ast_id) REFERENCES assets(ast_id)
);

-- ============================================================
-- FOREX
-- ============================================================
CREATE TABLE forex (
    for_ast_id INTEGER PRIMARY KEY,
    for_base_currency VARCHAR NOT NULL,
    for_quote_currency VARCHAR NOT NULL,
    CONSTRAINT fk_forex_asset
        FOREIGN KEY (for_ast_id) REFERENCES assets(ast_id)
);

-- ============================================================
-- COMMODITIES
-- ============================================================
CREATE TABLE commodities (
    com_ast_id INTEGER PRIMARY KEY,
    com_unit VARCHAR,
    com_contract_size DECIMAL(18,2),
    CONSTRAINT fk_commodities_asset
        FOREIGN KEY (com_ast_id) REFERENCES assets(ast_id)
);

-- ============================================================
-- FAVORITES
-- ============================================================
CREATE TABLE favorites (
    fav_usr_id INTEGER NOT NULL,
    fav_ast_id INTEGER NOT NULL,
    fav_created_at TIMESTAMP DEFAULT NOW(),

    PRIMARY KEY (fav_usr_id, fav_ast_id),

    CONSTRAINT fk_favorites_user
        FOREIGN KEY (fav_usr_id) REFERENCES users(usr_id),

    CONSTRAINT fk_favorites_asset
        FOREIGN KEY (fav_ast_id) REFERENCES assets(ast_id)
);

-- ============================================================
-- PORTFOLIOS
-- ============================================================
CREATE TABLE portfolios (
    prt_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prt_usr_id INTEGER NOT NULL,
    prt_name VARCHAR NOT NULL,
    prt_description TEXT,
    prt_strategy_type VARCHAR,
    prt_risk_tolerance VARCHAR DEFAULT 'medium',
    prt_max_position_size_pct DECIMAL(5,2) DEFAULT 5.00,
    prt_max_open_positions INTEGER DEFAULT 10,
    prt_base_currency VARCHAR DEFAULT 'USD',
    prt_is_active BOOLEAN DEFAULT TRUE,
    prt_created_at TIMESTAMP DEFAULT NOW(),
    prt_updated_at TIMESTAMP DEFAULT NOW(),

    CONSTRAINT fk_portfolios_user
        FOREIGN KEY (prt_usr_id) REFERENCES users(usr_id)
);

-- ============================================================
-- PORTFOLIO ASSETS
-- ============================================================
CREATE TABLE portfolio_assets (
    pas_prt_id INTEGER NOT NULL,
    pas_ast_id INTEGER NOT NULL,
    pas_is_active BOOLEAN DEFAULT TRUE,
    pas_created_at TIMESTAMP DEFAULT NOW(),

    PRIMARY KEY (pas_prt_id, pas_ast_id),

    CONSTRAINT fk_portfolio_assets_portfolio
        FOREIGN KEY (pas_prt_id) REFERENCES portfolios(prt_id),

    CONSTRAINT fk_portfolio_assets_asset
        FOREIGN KEY (pas_ast_id) REFERENCES assets(ast_id)
);

-- ============================================================
-- BOTS
-- ============================================================
CREATE TABLE bots (
    bot_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bot_name VARCHAR NOT NULL,
    bot_description TEXT,
    bot_prompt_template TEXT NOT NULL,
    bot_is_active BOOLEAN DEFAULT TRUE,
    bot_created_at TIMESTAMP DEFAULT NOW(),
    bot_updated_at TIMESTAMP DEFAULT NOW()
);

-- ============================================================
-- TRADING BOTS
-- ============================================================
CREATE TABLE trading_bots (
    trd_bot_id INTEGER PRIMARY KEY,
    CONSTRAINT fk_trading_bots_bot
        FOREIGN KEY (trd_bot_id) REFERENCES bots(bot_id)
);

-- ============================================================
-- SENTIMENT BOTS
-- ============================================================
CREATE TABLE sentiment_bots (
    sen_bot_id INTEGER PRIMARY KEY,
    CONSTRAINT fk_sentiment_bots_bot
        FOREIGN KEY (sen_bot_id) REFERENCES bots(bot_id)
);

-- ============================================================
-- ARBITRAGE BOTS
-- ============================================================
CREATE TABLE arbitrage_bots (
    arb_bot_id INTEGER PRIMARY KEY,
    CONSTRAINT fk_arbitrage_bots_bot
        FOREIGN KEY (arb_bot_id) REFERENCES bots(bot_id)
);

-- ============================================================
-- RISK BOTS
-- ============================================================
CREATE TABLE risk_bots (
    rsk_bot_id INTEGER PRIMARY KEY,
    CONSTRAINT fk_risk_bots_bot
        FOREIGN KEY (rsk_bot_id) REFERENCES bots(bot_id)
);

-- ============================================================
-- BOT PARAMETERS
-- ============================================================
CREATE TABLE bot_parameters (
    par_bot_id INTEGER NOT NULL,
    par_name VARCHAR NOT NULL,
    par_value TEXT,
    par_type VARCHAR NOT NULL,
    par_created_at TIMESTAMP DEFAULT NOW(),
    par_updated_at TIMESTAMP DEFAULT NOW(),

    PRIMARY KEY (par_bot_id, par_name),

    CONSTRAINT fk_bot_parameters_bot
        FOREIGN KEY (par_bot_id) REFERENCES bots(bot_id)
);

-- ============================================================
-- MARKET DATA
-- ============================================================
CREATE TABLE market_data (
    mkt_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mkt_ast_id INTEGER NOT NULL,
    mkt_timeframe VARCHAR NOT NULL,
    mkt_open DECIMAL(18,8) NOT NULL,
    mkt_high DECIMAL(18,8) NOT NULL,
    mkt_low DECIMAL(18,8) NOT NULL,
    mkt_close DECIMAL(18,8) NOT NULL,
    mkt_volume DECIMAL(18,8),
    mkt_timestamp TIMESTAMP NOT NULL,
    mkt_source VARCHAR,

    CONSTRAINT fk_market_data_asset
        FOREIGN KEY (mkt_ast_id) REFERENCES assets(ast_id),

    CONSTRAINT uq_market_data_asset_timeframe_timestamp
        UNIQUE (mkt_ast_id, mkt_timeframe, mkt_timestamp)
);

-- ============================================================
-- DATA SOURCES
-- ============================================================
CREATE TABLE data_sources (
    src_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    src_type VARCHAR NOT NULL,
    src_url VARCHAR,
    src_title TEXT,
    src_content TEXT,
    src_published_at TIMESTAMP,
    src_is_processed BOOLEAN DEFAULT FALSE,
    src_created_at TIMESTAMP DEFAULT NOW()
);

-- ============================================================
-- NEWS ARTICLES
-- ============================================================
CREATE TABLE news_articles (
    new_src_id INTEGER PRIMARY KEY,
    new_source VARCHAR,
    new_author VARCHAR,
    new_summary TEXT,

    CONSTRAINT fk_news_articles_source
        FOREIGN KEY (new_src_id) REFERENCES data_sources(src_id)
);

-- ============================================================
-- TWEETS / SOCIAL POSTS
-- ============================================================
CREATE TABLE tweets (
    twe_src_id INTEGER PRIMARY KEY,
    twe_tweet_id VARCHAR UNIQUE NOT NULL,
    twe_username VARCHAR NOT NULL,
    twe_verified BOOLEAN DEFAULT FALSE,
    twe_retweet_count INTEGER DEFAULT 0,
    twe_like_count INTEGER DEFAULT 0,

    CONSTRAINT fk_tweets_source
        FOREIGN KEY (twe_src_id) REFERENCES data_sources(src_id)
);

-- ============================================================
-- REPORTS
-- ============================================================
CREATE TABLE reports (
    rep_src_id INTEGER PRIMARY KEY,
    rep_type VARCHAR NOT NULL,
    rep_publisher VARCHAR NOT NULL,
    rep_industry VARCHAR,
    rep_company_name VARCHAR,
    rep_period_start DATE,
    rep_period_end DATE,
    rep_report_date DATE,

    CONSTRAINT fk_reports_source
        FOREIGN KEY (rep_src_id) REFERENCES data_sources(src_id)
);

-- ============================================================
-- ON-CHAIN DATA
-- ============================================================
CREATE TABLE onchain_data (
    onc_src_id INTEGER PRIMARY KEY,
    onc_blockchain VARCHAR NOT NULL,
    onc_tx_hash VARCHAR UNIQUE NOT NULL,
    onc_from_address VARCHAR,
    onc_to_address VARCHAR,
    onc_value DECIMAL(30,0),

    CONSTRAINT fk_onchain_data_source
        FOREIGN KEY (onc_src_id) REFERENCES data_sources(src_id)
);

-- ============================================================
-- SOURCE CLASSIFICATIONS
-- ============================================================
CREATE TABLE source_classifications (
    cls_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cls_src_id INTEGER NOT NULL,
    cls_category VARCHAR,
    cls_importance VARCHAR,
    cls_sentiment VARCHAR,
    cls_should_trigger BOOLEAN DEFAULT FALSE,
    cls_reason TEXT,
    cls_created_at TIMESTAMP DEFAULT NOW(),

    CONSTRAINT fk_source_classifications_source
        FOREIGN KEY (cls_src_id) REFERENCES data_sources(src_id)
);

-- ============================================================
-- CLASSIFICATION ASSETS
-- ============================================================
CREATE TABLE classification_assets (
    cla_cls_id INTEGER NOT NULL,
    cla_ast_id INTEGER NOT NULL,
    cla_relevance_confidence INTEGER,
    cla_reason TEXT,

    PRIMARY KEY (cla_cls_id, cla_ast_id),

    CONSTRAINT fk_classification_assets_classification
        FOREIGN KEY (cla_cls_id) REFERENCES source_classifications(cls_id),

    CONSTRAINT fk_classification_assets_asset
        FOREIGN KEY (cla_ast_id) REFERENCES assets(ast_id)
);

-- ============================================================
-- ANALYSES
-- ============================================================
CREATE TABLE analyses (
    anl_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    anl_bot_id INTEGER NOT NULL,
    anl_prt_id INTEGER,
    anl_ast_id INTEGER,
    anl_trigger_type VARCHAR NOT NULL,
    anl_trigger_reason TEXT,
    anl_prompt_text TEXT NOT NULL,
    anl_response_text TEXT NOT NULL,
    anl_summary TEXT,
    anl_direction VARCHAR,
    anl_market_sentiment VARCHAR,
    anl_confidence INTEGER,
    anl_risk_level VARCHAR,
    anl_timeframe VARCHAR,
    anl_created_at TIMESTAMP DEFAULT NOW(),

    CONSTRAINT fk_analyses_bot
        FOREIGN KEY (anl_bot_id) REFERENCES bots(bot_id),

    CONSTRAINT fk_analyses_portfolio
        FOREIGN KEY (anl_prt_id) REFERENCES portfolios(prt_id),

    CONSTRAINT fk_analyses_asset
        FOREIGN KEY (anl_ast_id) REFERENCES assets(ast_id)
);

-- ============================================================
-- ANALYSIS SOURCES
-- ============================================================
CREATE TABLE analysis_sources (
    ans_anl_id INTEGER NOT NULL,
    ans_src_id INTEGER NOT NULL,

    PRIMARY KEY (ans_anl_id, ans_src_id),

    CONSTRAINT fk_analysis_sources_analysis
        FOREIGN KEY (ans_anl_id) REFERENCES analyses(anl_id),

    CONSTRAINT fk_analysis_sources_source
        FOREIGN KEY (ans_src_id) REFERENCES data_sources(src_id)
);

-- ============================================================
-- ANALYSIS INPUTS
-- ============================================================
CREATE TABLE analysis_inputs (
    inp_anl_id INTEGER NOT NULL,
    inp_src_anl_id INTEGER NOT NULL,

    PRIMARY KEY (inp_anl_id, inp_src_anl_id),

    CONSTRAINT fk_analysis_inputs_analysis
        FOREIGN KEY (inp_anl_id) REFERENCES analyses(anl_id),

    CONSTRAINT fk_analysis_inputs_source_analysis
        FOREIGN KEY (inp_src_anl_id) REFERENCES analyses(anl_id)
);

-- ============================================================
-- SIGNALS
-- ============================================================
CREATE TABLE signals (
    sig_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sig_anl_id INTEGER NOT NULL,
    sig_prt_id INTEGER,
    sig_ast_id INTEGER NOT NULL,
    sig_action VARCHAR NOT NULL,
    sig_entry_price DECIMAL(18,8),
    sig_stop_loss_price DECIMAL(18,8),
    sig_take_profit_price DECIMAL(18,8),
    sig_confidence INTEGER,
    sig_timeframe VARCHAR,
    sig_status VARCHAR DEFAULT 'active',
    sig_expires_at TIMESTAMP,
    sig_created_at TIMESTAMP DEFAULT NOW(),

    CONSTRAINT fk_signals_analysis
        FOREIGN KEY (sig_anl_id) REFERENCES analyses(anl_id),

    CONSTRAINT fk_signals_portfolio
        FOREIGN KEY (sig_prt_id) REFERENCES portfolios(prt_id),

    CONSTRAINT fk_signals_asset
        FOREIGN KEY (sig_ast_id) REFERENCES assets(ast_id)
);

COMMIT;
