-- ============================================================
-- AI MARKET INTELLIGENCE PLATFORM
-- PostgreSQL Schema
--
-- IDENTITY vs SERIAL:
--
-- SERIAL:
-- - Ancienne syntaxe PostgreSQL.
-- - Crée automatiquement une séquence séparée.
-- - Fonctionne toujours, mais est moins explicite.
--
-- IDENTITY:
-- - Syntaxe SQL moderne et standard.
-- - Recommandée pour les nouveaux projets PostgreSQL.
-- - GENERATED BY DEFAULT permet également de fournir
--   manuellement un ID si nécessaire.
--
-- Ce schéma utilise donc :
--
-- INTEGER GENERATED BY DEFAULT AS IDENTITY
-- ============================================================


-- ============================================================
-- DROP EXISTING TABLES
--
-- Ordre inverse des dépendances.
-- CASCADE supprime également les contraintes dépendantes.
-- ============================================================

DROP TABLE IF EXISTS signals CASCADE;
DROP TABLE IF EXISTS analysis_inputs CASCADE;
DROP TABLE IF EXISTS analysis_sources CASCADE;
DROP TABLE IF EXISTS analyses CASCADE;

DROP TABLE IF EXISTS classification_assets CASCADE;
DROP TABLE IF EXISTS source_classifications CASCADE;

DROP TABLE IF EXISTS data_sources CASCADE;
DROP TABLE IF EXISTS market_data CASCADE;

DROP TABLE IF EXISTS prompts CASCADE;

DROP TABLE IF EXISTS portfolio_assets CASCADE;
DROP TABLE IF EXISTS portfolios CASCADE;

DROP TABLE IF EXISTS favorites CASCADE;

DROP TABLE IF EXISTS commodities CASCADE;
DROP TABLE IF EXISTS forex CASCADE;
DROP TABLE IF EXISTS crypto CASCADE;
DROP TABLE IF EXISTS stocks CASCADE;

DROP TABLE IF EXISTS assets CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- ============================================================
-- UTILISATEURS
-- ============================================================

CREATE TABLE users (
    usr_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    usr_username VARCHAR NOT NULL UNIQUE,
    usr_email VARCHAR NOT NULL UNIQUE,
    usr_password_hash VARCHAR NOT NULL,

    usr_is_active BOOLEAN NOT NULL DEFAULT TRUE,
    usr_created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    usr_role VARCHAR NOT NULL DEFAULT 'employe'

);


-- ============================================================
-- ACTIFS
-- ============================================================

CREATE TABLE assets (
    ast_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    ast_symbol VARCHAR NOT NULL UNIQUE,
    ast_name VARCHAR NOT NULL,
    ast_type VARCHAR NOT NULL,

    ast_is_active BOOLEAN NOT NULL DEFAULT TRUE,
    ast_created_at TIMESTAMP NOT NULL DEFAULT NOW()
);


-- ============================================================
-- FAVORIS
-- ============================================================

CREATE TABLE favorites (
    fav_usr_id INTEGER NOT NULL,
    fav_ast_id INTEGER NOT NULL,

    fav_created_at TIMESTAMP NOT NULL DEFAULT NOW(),

    PRIMARY KEY (
        fav_usr_id,
        fav_ast_id
    ),

    CONSTRAINT fk_favorites_user
        FOREIGN KEY (fav_usr_id)
        REFERENCES users(usr_id),

    CONSTRAINT fk_favorites_asset
        FOREIGN KEY (fav_ast_id)
        REFERENCES assets(ast_id)
);


-- ============================================================
-- ACTIONS
-- ============================================================

CREATE TABLE stocks (
    sto_ast_id INTEGER PRIMARY KEY,

    sto_exchange VARCHAR NOT NULL,
    sto_sector VARCHAR,
    sto_industry VARCHAR,

    CONSTRAINT fk_stocks_asset
        FOREIGN KEY (sto_ast_id)
        REFERENCES assets(ast_id)
);


-- ============================================================
-- CRYPTOMONNAIES
-- ============================================================

CREATE TABLE crypto (
    cry_ast_id INTEGER PRIMARY KEY,

    cry_blockchain VARCHAR,
    cry_contract_address VARCHAR,

    CONSTRAINT fk_crypto_asset
        FOREIGN KEY (cry_ast_id)
        REFERENCES assets(ast_id)
);


-- ============================================================
-- FOREX
-- ============================================================

CREATE TABLE forex (
    for_ast_id INTEGER PRIMARY KEY,

    for_base_currency VARCHAR NOT NULL,
    for_quote_currency VARCHAR NOT NULL,

    CONSTRAINT fk_forex_asset
        FOREIGN KEY (for_ast_id)
        REFERENCES assets(ast_id)
);


-- ============================================================
-- MATIÈRES PREMIÈRES
-- ============================================================

CREATE TABLE commodities (
    com_ast_id INTEGER PRIMARY KEY,

    com_unit VARCHAR,
    com_contract_size DECIMAL(18,2),

    CONSTRAINT fk_commodities_asset
        FOREIGN KEY (com_ast_id)
        REFERENCES assets(ast_id)
);


-- ============================================================
-- PORTEFEUILLES
-- ============================================================

CREATE TABLE portfolios (
    prt_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    prt_usr_id INTEGER NOT NULL,

    prt_name VARCHAR NOT NULL,
    prt_description TEXT,

    prt_strategy_type VARCHAR,
    prt_risk_tolerance VARCHAR DEFAULT 'medium',

    prt_max_position_size_pct DECIMAL(5,2) DEFAULT 5.00,
    prt_max_open_positions INTEGER DEFAULT 10,

    prt_base_currency VARCHAR DEFAULT 'USD',

    prt_is_active BOOLEAN DEFAULT TRUE,

    prt_created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    prt_updated_at TIMESTAMP NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_portfolios_user
        FOREIGN KEY (prt_usr_id)
        REFERENCES users(usr_id)
);


-- ============================================================
-- ACTIFS DU PORTEFEUILLE
-- ============================================================

CREATE TABLE portfolio_assets (
    pas_prt_id INTEGER NOT NULL,
    pas_ast_id INTEGER NOT NULL,

    pas_is_active BOOLEAN NOT NULL DEFAULT TRUE,
    pas_created_at TIMESTAMP NOT NULL DEFAULT NOW(),

    PRIMARY KEY (
        pas_prt_id,
        pas_ast_id
    ),

    CONSTRAINT fk_portfolio_assets_portfolio
        FOREIGN KEY (pas_prt_id)
        REFERENCES portfolios(prt_id),

    CONSTRAINT fk_portfolio_assets_asset
        FOREIGN KEY (pas_ast_id)
        REFERENCES assets(ast_id)
);


-- ============================================================
-- PROMPTS
-- ============================================================

CREATE TABLE prompts (
    prm_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    prm_name VARCHAR NOT NULL,
    prm_type VARCHAR NOT NULL,

    prm_version INTEGER DEFAULT 1,

    prm_prompt_text TEXT NOT NULL,

    prm_is_active BOOLEAN DEFAULT TRUE,

    prm_created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    prm_updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);


-- ============================================================
-- DONNÉES DE MARCHÉ
-- ============================================================

CREATE TABLE market_data (
    mkt_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    mkt_ast_id INTEGER NOT NULL,

    mkt_timeframe VARCHAR NOT NULL,

    mkt_open DECIMAL(18,8) NOT NULL,
    mkt_high DECIMAL(18,8) NOT NULL,
    mkt_low DECIMAL(18,8) NOT NULL,
    mkt_close DECIMAL(18,8) NOT NULL,

    mkt_volume DECIMAL(18,8),

    mkt_timestamp TIMESTAMP NOT NULL,
    mkt_source VARCHAR,

    CONSTRAINT fk_market_data_asset
        FOREIGN KEY (mkt_ast_id)
        REFERENCES assets(ast_id),

    CONSTRAINT uq_market_data_asset_timeframe_timestamp
        UNIQUE (
            mkt_ast_id,
            mkt_timeframe,
            mkt_timestamp
        )
);


-- ============================================================
-- SOURCES DE DONNÉES
-- ============================================================

CREATE TABLE data_sources (
    src_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    src_type VARCHAR NOT NULL,

    src_title TEXT,

    src_original_url VARCHAR,
    src_storage_path VARCHAR,
	src_content TEXT,
    src_published_at TIMESTAMP,

    src_is_processed BOOLEAN NOT NULL DEFAULT FALSE,

    src_created_at TIMESTAMP NOT NULL DEFAULT NOW()
);


-- ============================================================
-- CLASSIFICATIONS DES SOURCES
-- ============================================================

CREATE TABLE source_classifications (
    cls_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    cls_src_id INTEGER NOT NULL,
    cls_prm_id INTEGER NOT NULL,

    cls_category VARCHAR,
    cls_importance VARCHAR,
    cls_sentiment VARCHAR,

    cls_should_trigger BOOLEAN NOT NULL DEFAULT FALSE,
    cls_reason TEXT,

    cls_created_at TIMESTAMP NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_source_classifications_source
        FOREIGN KEY (cls_src_id)
        REFERENCES data_sources(src_id),

    CONSTRAINT fk_source_classifications_prompt
        FOREIGN KEY (cls_prm_id)
        REFERENCES prompts(prm_id)
);


-- ============================================================
-- ACTIFS DE LA CLASSIFICATION
-- ============================================================

CREATE TABLE classification_assets (
    cla_cls_id INTEGER NOT NULL,
    cla_ast_id INTEGER NOT NULL,

    cla_relevance_confidence INTEGER,
    cla_reason TEXT,

    PRIMARY KEY (
        cla_cls_id,
        cla_ast_id
    ),

    CONSTRAINT fk_classification_assets_classification
        FOREIGN KEY (cla_cls_id)
        REFERENCES source_classifications(cls_id),

    CONSTRAINT fk_classification_assets_asset
        FOREIGN KEY (cla_ast_id)
        REFERENCES assets(ast_id)
);


-- ============================================================
-- ANALYSES
-- ============================================================

CREATE TABLE analyses (
    anl_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    anl_prm_id INTEGER NOT NULL,

    anl_prt_id INTEGER,
    anl_ast_id INTEGER,

    anl_trigger_type VARCHAR NOT NULL,
    anl_trigger_reason TEXT,

    anl_response_text TEXT NOT NULL,
    anl_summary TEXT,

    anl_direction VARCHAR,
    anl_market_sentiment VARCHAR,
    anl_confidence INTEGER,
    anl_risk_level VARCHAR,

    anl_timeframe VARCHAR,

    anl_created_at TIMESTAMP NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_analyses_prompt
        FOREIGN KEY (anl_prm_id)
        REFERENCES prompts(prm_id),

    CONSTRAINT fk_analyses_portfolio
        FOREIGN KEY (anl_prt_id)
        REFERENCES portfolios(prt_id),

    CONSTRAINT fk_analyses_asset
        FOREIGN KEY (anl_ast_id)
        REFERENCES assets(ast_id)
);


-- ============================================================
-- SOURCES UTILISÉES PAR LES ANALYSES
-- ============================================================

CREATE TABLE analysis_sources (
    ans_anl_id INTEGER NOT NULL,
    ans_src_id INTEGER NOT NULL,

    PRIMARY KEY (
        ans_anl_id,
        ans_src_id
    ),

    CONSTRAINT fk_analysis_sources_analysis
        FOREIGN KEY (ans_anl_id)
        REFERENCES analyses(anl_id),

    CONSTRAINT fk_analysis_sources_source
        FOREIGN KEY (ans_src_id)
        REFERENCES data_sources(src_id)
);


-- ============================================================
-- ENTRÉES DES ANALYSES
-- ============================================================

CREATE TABLE analysis_inputs (
    inp_anl_id INTEGER NOT NULL,
    inp_src_anl_id INTEGER NOT NULL,

    PRIMARY KEY (
        inp_anl_id,
        inp_src_anl_id
    ),

    CONSTRAINT fk_analysis_inputs_analysis
        FOREIGN KEY (inp_anl_id)
        REFERENCES analyses(anl_id),

    CONSTRAINT fk_analysis_inputs_source_analysis
        FOREIGN KEY (inp_src_anl_id)
        REFERENCES analyses(anl_id)
);


-- ============================================================
-- SIGNAUX
-- ============================================================

CREATE TABLE signals (
    sig_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    sig_anl_id INTEGER NOT NULL,

    sig_prt_id INTEGER,
    sig_ast_id INTEGER NOT NULL,

    sig_action VARCHAR NOT NULL,

    sig_entry_price DECIMAL(18,8),
    sig_stop_loss_price DECIMAL(18,8),
    sig_take_profit_price DECIMAL(18,8),

    sig_confidence INTEGER,
    sig_timeframe VARCHAR,

    sig_status VARCHAR DEFAULT 'active',

    sig_expires_at TIMESTAMP,
    sig_created_at TIMESTAMP NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_signals_analysis
        FOREIGN KEY (sig_anl_id)
        REFERENCES analyses(anl_id),

    CONSTRAINT fk_signals_portfolio
        FOREIGN KEY (sig_prt_id)
        REFERENCES portfolios(prt_id),

    CONSTRAINT fk_signals_asset
        FOREIGN KEY (sig_ast_id)
        REFERENCES assets(ast_id)
);


COMMIT;