-- ============================================================
-- AI MARKET INTELLIGENCE PLATFORM
-- PostgreSQL Schema
--
-- IDENTITY vs SERIAL:
--
-- SERIAL:
-- - Ancienne syntaxe PostgreSQL.
-- - Crée automatiquement une séquence séparée.
-- - Fonctionne toujours, mais est moins explicite.
--
-- IDENTITY:
-- - Syntaxe SQL moderne et standard.
-- - Recommandée pour les nouveaux projets PostgreSQL.
-- - GENERATED BY DEFAULT permet également de fournir
--   manuellement un ID si nécessaire.
--
-- Ce schéma utilise donc :
--
-- INTEGER GENERATED BY DEFAULT AS IDENTITY
-- ============================================================


-- ============================================================
-- DROP EXISTING TABLES
--
-- Ordre inverse des dépendances.
-- CASCADE supprime également les contraintes dépendantes.
-- ============================================================

DROP TABLE IF EXISTS portfolio_strategist_runs CASCADE;
DROP TABLE IF EXISTS market_opportunity_events CASCADE;
DROP TABLE IF EXISTS portfolio_strategists CASCADE;
-- Compatibility cleanup for the short-lived first demo name.
DROP TABLE IF EXISTS portfolio_guardian_runs CASCADE;
DROP TABLE IF EXISTS portfolio_guardians CASCADE;
DROP TABLE IF EXISTS orchestrator_analysis_jobs CASCADE;
DROP TABLE IF EXISTS signals CASCADE;
DROP TABLE IF EXISTS analysis_inputs CASCADE;
DROP TABLE IF EXISTS analysis_sources CASCADE;
DROP TABLE IF EXISTS analysis_assets CASCADE;
DROP TABLE IF EXISTS analyses CASCADE;

DROP TABLE IF EXISTS classification_niches CASCADE;
DROP TABLE IF EXISTS classification_assets CASCADE;
DROP TABLE IF EXISTS source_classifications CASCADE;

DROP TABLE IF EXISTS asset_niches CASCADE;
DROP TABLE IF EXISTS niches CASCADE;

DROP TABLE IF EXISTS data_sources CASCADE;
DROP TABLE IF EXISTS market_data CASCADE;
DROP TABLE IF EXISTS rss_feed_runs CASCADE;
DROP TABLE IF EXISTS rss_feeds CASCADE;

DROP TABLE IF EXISTS prompts CASCADE;

DROP TABLE IF EXISTS transactions CASCADE;
DROP TABLE IF EXISTS portfolio_assets CASCADE;
DROP TABLE IF EXISTS portfolios CASCADE;

DROP TABLE IF EXISTS favorites CASCADE;

DROP TABLE IF EXISTS futures CASCADE;
DROP TABLE IF EXISTS commodities CASCADE;
DROP TABLE IF EXISTS forex CASCADE;
DROP TABLE IF EXISTS crypto CASCADE;
DROP TABLE IF EXISTS stocks CASCADE;

DROP TABLE IF EXISTS assets CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- ============================================================
-- UTILISATEURS
-- ============================================================

CREATE TABLE users (
    usr_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    usr_username VARCHAR NOT NULL UNIQUE,
    usr_email VARCHAR NOT NULL UNIQUE,
    usr_password_hash VARCHAR NOT NULL,

    usr_is_active BOOLEAN NOT NULL DEFAULT TRUE,
    usr_created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    usr_role VARCHAR NOT NULL DEFAULT 'employe'

);


-- ============================================================
-- ACTIFS
-- ============================================================

CREATE TABLE assets (
    ast_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Identité Yahoo Finance de l'actif.
    ast_symbol VARCHAR NOT NULL UNIQUE,
    ast_name VARCHAR NOT NULL,

    -- Type normalisé utilisé par FAAH.
    ast_type VARCHAR NOT NULL,

    -- Type original retourné par Yahoo Finance.
    ast_yahoo_type VARCHAR,

    -- Informations générales de négociation.
    ast_exchange VARCHAR,
    ast_currency VARCHAR,
    ast_country VARCHAR,
    ast_logo BYTEA,
    ast_logo_mime_type VARCHAR,
    ast_logo_last_attempt_at TIMESTAMPTZ,

    -- Indique si le marché en direct doit suivre cet actif.
    ast_is_tracked BOOLEAN NOT NULL DEFAULT FALSE,

    ast_created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ast_updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_asset_type
        CHECK (
            ast_type IN (
                'stock',
                'crypto',
                'forex',
                'future'
            )
        )
);


-- ============================================================
-- FAVORIS
-- ============================================================

CREATE TABLE favorites (
    fav_usr_id INTEGER NOT NULL,
    fav_ast_id INTEGER NOT NULL,

    fav_created_at TIMESTAMP NOT NULL DEFAULT NOW(),

    PRIMARY KEY (
        fav_usr_id,
        fav_ast_id
    ),

    CONSTRAINT fk_favorites_user
        FOREIGN KEY (fav_usr_id)
        REFERENCES users(usr_id),

    CONSTRAINT fk_favorites_asset
        FOREIGN KEY (fav_ast_id)
        REFERENCES assets(ast_id)
);


-- ============================================================
-- ACTIONS
-- ============================================================

CREATE TABLE stocks (
    sto_ast_id INTEGER PRIMARY KEY,

    sto_sector VARCHAR,
    sto_industry VARCHAR,

    CONSTRAINT fk_stocks_asset
        FOREIGN KEY (sto_ast_id)
        REFERENCES assets(ast_id)
        ON DELETE CASCADE
);


-- ============================================================
-- CRYPTOMONNAIES
-- ============================================================

CREATE TABLE crypto (
    cry_ast_id INTEGER PRIMARY KEY,

    cry_base_currency VARCHAR,
    cry_quote_currency VARCHAR,

    cry_blockchain VARCHAR,
    cry_contract_address VARCHAR,

    CONSTRAINT fk_crypto_asset
        FOREIGN KEY (cry_ast_id)
        REFERENCES assets(ast_id)
        ON DELETE CASCADE
);


-- ============================================================
-- FOREX
-- ============================================================

CREATE TABLE forex (
    for_ast_id INTEGER PRIMARY KEY,

    for_base_currency VARCHAR NOT NULL,
    for_quote_currency VARCHAR NOT NULL,

    CONSTRAINT fk_forex_asset
        FOREIGN KEY (for_ast_id)
        REFERENCES assets(ast_id)
        ON DELETE CASCADE
);


-- ============================================================
-- MATIÈRES PREMIÈRES
-- ============================================================

CREATE TABLE futures (
    fut_ast_id INTEGER PRIMARY KEY,

    -- Actif sous-jacent, par exemple Or ou Pétrole WTI.
    fut_underlying_name VARCHAR,

    -- Type du sous-jacent : matière première, devise,
    -- indice ou taux d'intérêt.
    fut_underlying_type VARCHAR,

    fut_unit VARCHAR,
    fut_contract_size DECIMAL(18,2),

    CONSTRAINT fk_futures_asset
        FOREIGN KEY (fut_ast_id)
        REFERENCES assets(ast_id)
        ON DELETE CASCADE
);

-- ============================================================
-- NICHES
-- ============================================================

CREATE TABLE niches (
    nic_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nic_name VARCHAR NOT NULL UNIQUE,
    nic_category VARCHAR NOT NULL,
    nic_description TEXT NOT NULL
);

INSERT INTO niches (nic_name, nic_category, nic_description) VALUES
    (
        'Hyperscalers & Big Tech Monopolies',
        'Technology & AI',
        'Dominant global technology platforms operating cloud, advertising, commerce, device or digital-service ecosystems.'
    ),
    (
        'AI Hardware, Accelerators & Connective Tissue',
        'Technology & AI',
        'Designers and suppliers of processors, accelerators and interconnect technologies used to build AI systems.'
    ),
    (
        'Data Center Infrastructure & Networking',
        'Technology & AI',
        'Companies supplying data-center computing, networking, cooling, power management and related infrastructure.'
    ),
    (
        'Semiconductor Equipment & "Picks and Shovels"',
        'Technology & AI',
        'Suppliers of semiconductor manufacturing equipment, materials, design tools and other essential production inputs.'
    ),
    (
        'High-Bandwidth Memory (HBM) & Storage',
        'Technology & AI',
        'Producers of high-performance memory, storage products and technologies supporting data-intensive computing.'
    ),
    (
        'Enterprise Software & Vertical SaaS',
        'Technology & AI',
        'Software providers serving businesses through general enterprise platforms or industry-specific subscription products.'
    ),
    (
        'The "Electrification" Base Metals',
        'Energy, Resources & Real Assets',
        'Producers and processors of copper, lithium and other materials required for electrification.'
    ),
    (
        'Nuclear Energy & Uranium',
        'Energy, Resources & Real Assets',
        'Uranium miners, nuclear fuel suppliers, reactor developers and nuclear power operators.'
    ),
    (
        'Traditional Energy Supermajors & E&P',
        'Energy, Resources & Real Assets',
        'Large integrated energy companies and businesses focused on oil and gas exploration and production.'
    ),
    (
        'Gold & Safe Haven Assets',
        'Energy, Resources & Real Assets',
        'Gold producers and assets commonly used as stores of value during financial or geopolitical uncertainty.'
    ),
    (
        'Asset-Light Royalties & Midstream',
        'Energy, Resources & Real Assets',
        'Royalty, streaming, pipeline, transport and storage businesses earning from resource production and movement.'
    ),
    (
        'GLP-1s & Metabolic Leaders',
        'Healthcare & Biotechnology',
        'Companies leading obesity, diabetes and metabolic-disease treatment, including GLP-1 therapies.'
    ),
    (
        'Innovative Therapeutics & Generics',
        'Healthcare & Biotechnology',
        'Developers and manufacturers of novel medicines, biotechnology treatments and generic pharmaceuticals.'
    ),
    (
        'Social Media, Creators & Streaming',
        'Digital Consumer, Auto & Connectivity',
        'Platforms monetizing social interaction, creator content, video, music and other streamed media.'
    ),
    (
        'Global Automotive & Smart Mobility',
        'Digital Consumer, Auto & Connectivity',
        'Vehicle manufacturers and suppliers focused on electric, autonomous, connected and shared mobility.'
    ),
    (
        'Telecommunications Infrastructure',
        'Digital Consumer, Auto & Connectivity',
        'Operators and suppliers of wireless, broadband, tower, fiber and communications-network infrastructure.'
    ),
    (
        'Digital Classifieds & Marketplaces',
        'Digital Consumer, Auto & Connectivity',
        'Online platforms connecting buyers and sellers through listings, marketplaces and transaction services.'
    ),
    (
        'Aerospace, Defense & Traditional Tech Hardware',
        'Industrials & Financials',
        'Aerospace and defense contractors and manufacturers of established enterprise or consumer hardware.'
    ),
    (
        'Banking & Financial Services',
        'Industrials & Financials',
        'Banks, payment providers, brokers, exchanges, insurers and other financial-service businesses.'
    ),
    (
        'Central Banks, Interest Rates & Sovereign Bonds',
        'Macroeconomics & Policy',
        'Monetary-policy decisions, central-bank communication, interest-rate expectations, sovereign debt and rate-sensitive assets.'
    ),
    (
        'Inflation, Labor Markets & Economic Growth',
        'Macroeconomics & Policy',
        'Inflation, employment, wages, consumer activity, business cycles and other economic data that can move financial markets.'
    ),
    (
        'Financial Regulation, Enforcement & Compliance',
        'Macroeconomics & Policy',
        'Financial rules, investigations, enforcement actions, litigation and compliance developments affecting companies and markets.'
    ),
    (
        'Corporate Earnings, Guidance & SEC Filings',
        'Corporate Events & Capital Markets',
        'Earnings results, forecasts and material company disclosures found in 8-K, 10-Q, 10-K and equivalent regulatory filings.'
    ),
    (
        'M&A, Activism & Corporate Governance',
        'Corporate Events & Capital Markets',
        'Mergers, acquisitions, divestitures, activist campaigns, leadership changes, proxy matters and major governance events.'
    ),
    (
        'IPOs, Venture Capital & Private Markets',
        'Corporate Events & Capital Markets',
        'Startup funding, private-market valuations, initial public offerings and other private-to-public capital formation.'
    ),
    (
        'Crypto Assets, Exchanges & Blockchain Infrastructure',
        'Digital Assets & Fintech',
        'Cryptoassets, trading venues, custody, stablecoins, decentralized protocols and infrastructure supporting blockchain networks.'
    ),
    (
        'Fintech, Payments & Digital Banking',
        'Digital Assets & Fintech',
        'Payment networks, financial software, digital banks, lending platforms and technology-led financial services.'
    ),
    (
        'Renewable Energy, Utilities & Grid Infrastructure',
        'Energy, Resources & Real Assets',
        'Renewable power developers, regulated utilities, electricity markets, storage and transmission or distribution infrastructure.'
    ),
    (
        'Energy Markets, Inventories & Commodity Flows',
        'Energy, Resources & Real Assets',
        'Oil, natural-gas and power-market balances, inventories, production, demand, trade flows and commodity pricing.'
    ),
    (
        'Real Estate, REITs & Housing',
        'Energy, Resources & Real Assets',
        'Property companies, real-estate investment trusts, housing markets, construction activity and rate-sensitive property finance.'
    ),
    (
        'Cybersecurity & Digital Resilience',
        'Technology & AI',
        'Security software, identity, cloud protection and businesses exposed to major cyber incidents or digital-resilience spending.'
    ),
    (
        'Industrial Automation, Robotics & Supply Chains',
        'Industrials & Financials',
        'Automation, robotics, logistics, manufacturing technology and supply-chain infrastructure or disruption.'
    ),
    (
        'Consumer, Retail & E-Commerce',
        'Digital Consumer, Auto & Connectivity',
        'Retailers, consumer brands, online commerce platforms and businesses driven by household demand and spending trends.'
    ),
    (
        'Other / Unclassified',
        'Other',
        'Fallback for an asset that does not yet have a clear match in the curated niche taxonomy.'
    )
ON CONFLICT (nic_name) DO UPDATE SET
    nic_category = EXCLUDED.nic_category,
    nic_description = EXCLUDED.nic_description;

-- ============================================================
-- NICHES ASSETS
-- ============================================================

CREATE TABLE asset_niches (
    ani_ast_id INTEGER NOT NULL,
    ani_nic_id INTEGER NOT NULL,
    ani_prm_id INTEGER,

    PRIMARY KEY (
        ani_ast_id,
        ani_nic_id
    ),

    CONSTRAINT fk_asset_niches_asset
        FOREIGN KEY (ani_ast_id)
        REFERENCES assets(ast_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_asset_niches_niche
        FOREIGN KEY (ani_nic_id)
        REFERENCES niches(nic_id)
        ON DELETE CASCADE
);

-- ============================================================
-- PORTEFEUILLES
-- ============================================================

CREATE TABLE portfolios (
    prt_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Un utilisateur possède un seul portefeuille.
    prt_usr_id INTEGER NOT NULL UNIQUE,

    prt_name VARCHAR NOT NULL,
    prt_description TEXT,

    prt_strategy_type VARCHAR,
    prt_risk_tolerance VARCHAR DEFAULT 'medium',

    prt_max_position_size_pct DECIMAL(5,2) DEFAULT 5.00,
    prt_max_open_positions INTEGER DEFAULT 10,

    prt_base_currency VARCHAR DEFAULT 'USD',

    prt_is_active BOOLEAN DEFAULT TRUE,

    prt_created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    prt_updated_at TIMESTAMP NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_portfolios_user
        FOREIGN KEY (prt_usr_id)
        REFERENCES users(usr_id)
);


-- ============================================================
-- ACTIFS DU PORTEFEUILLE
-- ============================================================

CREATE TABLE portfolio_assets (
    pas_prt_id INTEGER NOT NULL,
    pas_ast_id INTEGER NOT NULL,

    pas_quantity DECIMAL(18,8) NOT NULL DEFAULT 0,
    pas_average_purchase_price DECIMAL(18,8) NOT NULL DEFAULT 0,

    pas_is_active BOOLEAN NOT NULL DEFAULT TRUE,
    pas_created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    pas_updated_at TIMESTAMP NOT NULL DEFAULT NOW(),

    PRIMARY KEY (
        pas_prt_id,
        pas_ast_id
    ),

    CONSTRAINT fk_portfolio_assets_portfolio
        FOREIGN KEY (pas_prt_id)
        REFERENCES portfolios(prt_id),

    CONSTRAINT fk_portfolio_assets_asset
        FOREIGN KEY (pas_ast_id)
        REFERENCES assets(ast_id)
);


-- ============================================================
-- TRANSACTIONS
-- Une ligne est créée seulement lors d'un achat ou d'une vente.
-- ============================================================

CREATE TABLE transactions (
    id_trans INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    prt_id_trans INTEGER NOT NULL,
    ast_id_trans INTEGER NOT NULL,

    type_trans VARCHAR(10) NOT NULL
        CHECK (type_trans IN ('buy', 'sell')),
    quantity_trans NUMERIC(18,8) NOT NULL
        CHECK (quantity_trans > 0),
    price_trans NUMERIC(18,8) NOT NULL
        CHECK (price_trans > 0),
    fees_trans NUMERIC(18,8) NOT NULL DEFAULT 0
        CHECK (fees_trans >= 0),
    currency_trans VARCHAR(10) NOT NULL DEFAULT 'USD'
        CHECK (currency_trans = 'USD'),
    "createdAt_trans" TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_transactions_portfolio
        FOREIGN KEY (prt_id_trans)
        REFERENCES portfolios(prt_id),

    CONSTRAINT fk_transactions_asset
        FOREIGN KEY (ast_id_trans)
        REFERENCES assets(ast_id)
);


-- ============================================================
-- PROMPTS
-- ============================================================

CREATE TABLE prompts (
    prm_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    prm_name VARCHAR NOT NULL,
    prm_type VARCHAR NOT NULL,

    prm_version INTEGER DEFAULT 1,

    prm_prompt_text TEXT NOT NULL,

    prm_is_active BOOLEAN DEFAULT TRUE,

    prm_created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    prm_updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

ALTER TABLE asset_niches
    ADD CONSTRAINT fk_asset_niches_prompt
    FOREIGN KEY (ani_prm_id)
    REFERENCES prompts(prm_id)
    ON DELETE SET NULL;


-- ============================================================
-- FLUX RSS ET ÉTAT DU PLANIFICATEUR
-- PostgreSQL est la source de vérité pour la configuration et le planning.
-- ============================================================

CREATE TABLE rss_feeds (
    rsf_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rsf_name VARCHAR NOT NULL UNIQUE,
    rsf_url TEXT NOT NULL,
    rsf_source_prefix VARCHAR NOT NULL,
    rsf_poll_interval_seconds INTEGER NOT NULL DEFAULT 3600,
    rsf_status VARCHAR NOT NULL DEFAULT 'active',
    rsf_last_polled_at TIMESTAMPTZ,
    rsf_next_poll_at TIMESTAMPTZ,
    rsf_next_poll_trigger VARCHAR NOT NULL DEFAULT 'schedule',
    rsf_pending_instruction_id VARCHAR,
    rsf_last_status VARCHAR,
    rsf_last_items_processed INTEGER NOT NULL DEFAULT 0,
    rsf_last_error TEXT,
    rsf_created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    rsf_updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_rss_feed_poll_interval
        CHECK (rsf_poll_interval_seconds BETWEEN 300 AND 7200),
    CONSTRAINT chk_rss_feed_status
        CHECK (rsf_status IN ('active', 'paused')),
    CONSTRAINT chk_rss_feed_next_trigger
        CHECK (rsf_next_poll_trigger IN ('schedule', 'run_now'))
);

CREATE INDEX idx_rss_feeds_due
    ON rss_feeds (rsf_status, rsf_next_poll_at);

CREATE TABLE rss_feed_runs (
    rfr_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rfr_rsf_id INTEGER NOT NULL,
    rfr_trigger VARCHAR NOT NULL,
    rfr_instruction_id VARCHAR,
    rfr_status VARCHAR NOT NULL,
    rfr_started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    rfr_completed_at TIMESTAMPTZ,
    rfr_items_processed INTEGER NOT NULL DEFAULT 0,
    rfr_error TEXT,

    CONSTRAINT fk_rss_feed_runs_feed
        FOREIGN KEY (rfr_rsf_id)
        REFERENCES rss_feeds(rsf_id)
        ON DELETE CASCADE,
    CONSTRAINT chk_rss_feed_run_trigger
        CHECK (rfr_trigger IN ('schedule', 'run_now')),
    CONSTRAINT chk_rss_feed_run_status
        CHECK (rfr_status IN ('running', 'succeeded', 'failed'))
);

CREATE INDEX idx_rss_feed_runs_feed_started
    ON rss_feed_runs (rfr_rsf_id, rfr_started_at DESC);

INSERT INTO rss_feeds (
    rsf_name,
    rsf_url,
    rsf_source_prefix,
    rsf_poll_interval_seconds,
    rsf_next_poll_at
) VALUES
    ('Investing.com', 'https://www.investing.com/rss/news_25.rss', 'rss:investing', 3600, NOW()),
    ('Google Tech News', 'https://news.google.com/rss/search?q=technology+stocks&hl=en-US&gl=US&ceid=US:en', 'rss:google', 3600, NOW()),
    ('Oil and Energy', 'https://news.google.com/rss/search?q=oil+prices+crude+oil+energy+stocks&hl=en-US&gl=US&ceid=US:en', 'rss:google', 3600, NOW()),
    ('Gold and Mining', 'https://news.google.com/rss/search?q=gold+prices+gold+mining+stocks&hl=en-US&gl=US&ceid=US:en', 'rss:google', 3600, NOW()),
    ('Mergers and Acquisitions', 'https://news.google.com/rss/search?q=mergers+acquisitions+takeovers+stocks&hl=en-US&gl=US&ceid=US:en', 'rss:google', 3600, NOW()),
    ('Federal Reserve Press Releases', 'https://www.federalreserve.gov/feeds/press_all.xml', 'rss:federal-reserve', 3600, NOW()),
    ('SEC Press Releases', 'https://www.sec.gov/news/pressreleases.rss', 'rss:sec', 3600, NOW()),
    ('SEC EDGAR 8-K Filings', 'https://www.sec.gov/cgi-bin/browse-edgar?action=getcurrent&type=8-K&owner=exclude&count=100&output=atom', 'rss:sec-edgar', 3600, NOW()),
    ('ECB Communications', 'https://www.ecb.europa.eu/rss/press.html', 'rss:ecb', 3600, NOW()),
    ('BLS Latest Releases', 'https://www.bls.gov/feed/bls_latest.rss', 'rss:bls', 3600, NOW()),
    ('EIA Today in Energy', 'https://www.eia.gov/rss/todayinenergy.xml', 'rss:eia', 3600, NOW()),
    ('Bloomberg Markets', 'https://feeds.bloomberg.com/markets/news.rss', 'rss:bloomberg', 3600, NOW()),
    ('CNBC Top News', 'https://www.cnbc.com/id/100003114/device/rss/rss.html', 'rss:cnbc', 3600, NOW()),
    ('BBC Business', 'https://feeds.bbci.co.uk/news/business/rss.xml', 'rss:bbc', 3600, NOW()),
    ('TechCrunch', 'https://techcrunch.com/feed/', 'rss:techcrunch', 3600, NOW()),
    ('CoinDesk', 'https://www.coindesk.com/arc/outboundfeeds/rss/', 'rss:coindesk', 3600, NOW())
ON CONFLICT (rsf_name) DO UPDATE SET
    rsf_url = EXCLUDED.rsf_url,
    rsf_source_prefix = EXCLUDED.rsf_source_prefix,
    rsf_updated_at = NOW();


-- ============================================================
-- SOURCES DE DONNÉES
-- ============================================================

CREATE TABLE data_sources (
    src_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    src_type VARCHAR NOT NULL,

    src_title TEXT,

    src_original_url VARCHAR,
    src_storage_path VARCHAR,
	src_content TEXT,
    src_published_at TIMESTAMP,

    src_is_processed BOOLEAN NOT NULL DEFAULT FALSE,

    src_created_at TIMESTAMP NOT NULL DEFAULT NOW()
);


-- ============================================================
-- CLASSIFICATIONS DES SOURCES
-- ============================================================

CREATE TABLE source_classifications (
    cls_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    cls_src_id INTEGER NOT NULL,
    cls_prm_id INTEGER NOT NULL,

    cls_category VARCHAR,
    cls_importance VARCHAR,
    cls_sentiment VARCHAR,

    cls_should_trigger BOOLEAN NOT NULL DEFAULT FALSE,
    cls_reason TEXT,

    cls_created_at TIMESTAMP NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_source_classifications_source
        FOREIGN KEY (cls_src_id)
        REFERENCES data_sources(src_id),

    CONSTRAINT fk_source_classifications_prompt
        FOREIGN KEY (cls_prm_id)
        REFERENCES prompts(prm_id)
);


-- ============================================================
-- NICHES DE LA CLASSIFICATION
-- ============================================================

CREATE TABLE classification_niches (
    cln_cls_id INTEGER NOT NULL,
    cln_nic_id INTEGER NOT NULL,

    PRIMARY KEY (
        cln_cls_id,
        cln_nic_id
    ),

    CONSTRAINT fk_classification_niches_classification
        FOREIGN KEY (cln_cls_id)
        REFERENCES source_classifications(cls_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_classification_niches_niche
        FOREIGN KEY (cln_nic_id)
        REFERENCES niches(nic_id)
        ON DELETE CASCADE
);


-- ============================================================
-- ACTIFS DE LA CLASSIFICATION
-- ============================================================

CREATE TABLE classification_assets (
    cla_cls_id INTEGER NOT NULL,
    cla_ast_id INTEGER NOT NULL,
    cla_prm_id INTEGER,

    cla_relevance_confidence INTEGER,
    cla_reason TEXT,

    PRIMARY KEY (
        cla_cls_id,
        cla_ast_id
    ),

    CONSTRAINT fk_classification_assets_classification
        FOREIGN KEY (cla_cls_id)
        REFERENCES source_classifications(cls_id),

    CONSTRAINT fk_classification_assets_asset
        FOREIGN KEY (cla_ast_id)
        REFERENCES assets(ast_id),

    CONSTRAINT fk_classification_assets_prompt
        FOREIGN KEY (cla_prm_id)
        REFERENCES prompts(prm_id)
        ON DELETE SET NULL
);


-- ============================================================
-- ANALYSES
-- ============================================================

CREATE TABLE analyses (
    anl_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    anl_prm_id INTEGER NOT NULL,
    anl_cls_id INTEGER,
    anl_prt_id INTEGER,
    anl_ast_id INTEGER,

    anl_trigger_type VARCHAR NOT NULL,
    anl_trigger_reason TEXT,

    anl_response_text TEXT NOT NULL,
    anl_summary TEXT,

    anl_direction VARCHAR,
    anl_market_sentiment VARCHAR,
    anl_confidence INTEGER,
    anl_risk_level VARCHAR,

    anl_timeframe VARCHAR,

    anl_created_at TIMESTAMP NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_analyses_prompt
        FOREIGN KEY (anl_prm_id)
        REFERENCES prompts(prm_id),

    CONSTRAINT fk_analyses_portfolio
        FOREIGN KEY (anl_prt_id)
        REFERENCES portfolios(prt_id),

    CONSTRAINT fk_analyses_classification
        FOREIGN KEY (anl_cls_id)
        REFERENCES source_classifications(cls_id)
        ON DELETE SET NULL,

    CONSTRAINT fk_analyses_asset
        FOREIGN KEY (anl_ast_id)
        REFERENCES assets(ast_id)
);


-- ============================================================
-- ACTIFS ÉVALUÉS PAR LES ANALYSES
-- ============================================================

CREATE TABLE analysis_assets (
    aas_anl_id INTEGER NOT NULL,
    aas_ast_id INTEGER NOT NULL,

    aas_direction VARCHAR,
    aas_confidence INTEGER,
    aas_timeframe VARCHAR,
    aas_reason TEXT,
    aas_price_context JSONB,

    PRIMARY KEY (
        aas_anl_id,
        aas_ast_id
    ),

    CONSTRAINT fk_analysis_assets_analysis
        FOREIGN KEY (aas_anl_id)
        REFERENCES analyses(anl_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_analysis_assets_asset
        FOREIGN KEY (aas_ast_id)
        REFERENCES assets(ast_id)
        ON DELETE CASCADE
);


-- ============================================================
-- SOURCES UTILISÉES PAR LES ANALYSES
-- ============================================================

CREATE TABLE analysis_sources (
    ans_anl_id INTEGER NOT NULL,
    ans_src_id INTEGER NOT NULL,

    PRIMARY KEY (
        ans_anl_id,
        ans_src_id
    ),

    CONSTRAINT fk_analysis_sources_analysis
        FOREIGN KEY (ans_anl_id)
        REFERENCES analyses(anl_id),

    CONSTRAINT fk_analysis_sources_source
        FOREIGN KEY (ans_src_id)
        REFERENCES data_sources(src_id)
);


-- ============================================================
-- ENTRÉES DES ANALYSES
-- ============================================================

CREATE TABLE analysis_inputs (
    inp_anl_id INTEGER NOT NULL,
    inp_src_anl_id INTEGER NOT NULL,

    PRIMARY KEY (
        inp_anl_id,
        inp_src_anl_id
    ),

    CONSTRAINT fk_analysis_inputs_analysis
        FOREIGN KEY (inp_anl_id)
        REFERENCES analyses(anl_id),

    CONSTRAINT fk_analysis_inputs_source_analysis
        FOREIGN KEY (inp_src_anl_id)
        REFERENCES analyses(anl_id)
);


-- ============================================================
-- ANALYSES DE SUIVI DEMANDÉES PAR L'ORCHESTRATEUR
-- ============================================================

CREATE TABLE orchestrator_analysis_jobs (
    oaj_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    oaj_ast_id INTEGER NOT NULL,
    oaj_result_anl_id INTEGER,
    oaj_question TEXT NOT NULL,
    oaj_reason TEXT NOT NULL,
    oaj_priority INTEGER NOT NULL,
    oaj_status VARCHAR NOT NULL DEFAULT 'pending',
    oaj_error TEXT,
    oaj_requested_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    oaj_started_at TIMESTAMPTZ,
    oaj_completed_at TIMESTAMPTZ,

    CONSTRAINT fk_orchestrator_analysis_jobs_asset
        FOREIGN KEY (oaj_ast_id)
        REFERENCES assets(ast_id),

    CONSTRAINT fk_orchestrator_analysis_jobs_result
        FOREIGN KEY (oaj_result_anl_id)
        REFERENCES analyses(anl_id)
        ON DELETE SET NULL,

    CONSTRAINT chk_orchestrator_analysis_job_status
        CHECK (oaj_status IN ('pending', 'running', 'succeeded', 'failed')),

    CONSTRAINT chk_orchestrator_analysis_job_priority
        CHECK (oaj_priority BETWEEN 1 AND 5)
);

CREATE INDEX idx_orchestrator_analysis_jobs_status_requested
    ON orchestrator_analysis_jobs (oaj_status, oaj_requested_at);


-- ============================================================
-- SIGNAUX
-- ============================================================

CREATE TABLE signals (
    sig_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    sig_anl_id INTEGER NOT NULL,

    sig_prt_id INTEGER,
    sig_ast_id INTEGER NOT NULL,

    sig_action VARCHAR NOT NULL,

    sig_entry_price DECIMAL(18,8),
    sig_stop_loss_price DECIMAL(18,8),
    sig_take_profit_price DECIMAL(18,8),

    sig_confidence INTEGER,
    sig_timeframe VARCHAR,

    sig_status VARCHAR DEFAULT 'active',

    sig_expires_at TIMESTAMP,
    sig_created_at TIMESTAMP NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_signals_analysis
        FOREIGN KEY (sig_anl_id)
        REFERENCES analyses(anl_id),

    CONSTRAINT fk_signals_portfolio
        FOREIGN KEY (sig_prt_id)
        REFERENCES portfolios(prt_id),

    CONSTRAINT fk_signals_asset
        FOREIGN KEY (sig_ast_id)
        REFERENCES assets(ast_id)
);


-- ============================================================
-- PORTFOLIO STRATEGISTS AND MARKET OPPORTUNITY EVENTS
-- ============================================================

CREATE TABLE portfolio_strategists (
    pst_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pst_prt_id INTEGER NOT NULL UNIQUE
        REFERENCES portfolios(prt_id) ON DELETE CASCADE,
    pst_status VARCHAR NOT NULL DEFAULT 'active',
    pst_instructions TEXT,
    pst_last_signal_id INTEGER NOT NULL DEFAULT 0,
    pst_last_full_review_at TIMESTAMPTZ,
    pst_next_full_review_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    pst_last_summary TEXT,
    pst_created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    pst_updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_portfolio_strategist_status
        CHECK (pst_status IN ('active', 'paused'))
);

CREATE INDEX idx_portfolio_strategists_due
    ON portfolio_strategists (pst_status, pst_next_full_review_at);

CREATE TABLE market_opportunity_events (
    moe_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    moe_ast_id INTEGER NOT NULL REFERENCES assets(ast_id) ON DELETE CASCADE,
    moe_result_anl_id INTEGER REFERENCES analyses(anl_id) ON DELETE SET NULL,
    moe_event_type VARCHAR NOT NULL,
    moe_price_before NUMERIC(18,8) NOT NULL,
    moe_price_after NUMERIC(18,8) NOT NULL,
    moe_change_pct NUMERIC(10,4) NOT NULL,
    moe_window_seconds INTEGER NOT NULL,
    moe_reason TEXT NOT NULL,
    moe_status VARCHAR NOT NULL DEFAULT 'detected',
    moe_error TEXT,
    moe_detected_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    moe_analyzed_at TIMESTAMPTZ,
    CONSTRAINT chk_market_opportunity_event_type
        CHECK (moe_event_type IN ('price_rise', 'price_drop')),
    CONSTRAINT chk_market_opportunity_event_status
        CHECK (moe_status IN ('detected', 'analyzing', 'analyzed', 'notified', 'failed'))
);

CREATE INDEX idx_market_opportunity_events_status
    ON market_opportunity_events (moe_status, moe_detected_at);

CREATE TABLE portfolio_strategist_runs (
    psr_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    psr_pst_id INTEGER NOT NULL
        REFERENCES portfolio_strategists(pst_id) ON DELETE CASCADE,
    psr_ast_id INTEGER REFERENCES assets(ast_id) ON DELETE SET NULL,
    psr_sig_id INTEGER REFERENCES signals(sig_id) ON DELETE SET NULL,
    psr_moe_id INTEGER REFERENCES market_opportunity_events(moe_id) ON DELETE SET NULL,
    psr_result_anl_id INTEGER REFERENCES analyses(anl_id) ON DELETE SET NULL,
    psr_prm_id INTEGER REFERENCES prompts(prm_id) ON DELETE SET NULL,
    psr_review_type VARCHAR NOT NULL,
    psr_status VARCHAR NOT NULL DEFAULT 'pending',
    psr_priority INTEGER NOT NULL DEFAULT 3,
    psr_reason TEXT NOT NULL,
    psr_decision JSONB,
    psr_error TEXT,
    psr_created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    psr_started_at TIMESTAMPTZ,
    psr_completed_at TIMESTAMPTZ,
    CONSTRAINT chk_portfolio_strategist_run_type
        CHECK (psr_review_type IN ('targeted_signal', 'targeted_price', 'full')),
    CONSTRAINT chk_portfolio_strategist_run_status
        CHECK (psr_status IN ('pending', 'running', 'succeeded', 'failed', 'merged')),
    CONSTRAINT chk_portfolio_strategist_run_priority
        CHECK (psr_priority BETWEEN 1 AND 5)
);

CREATE INDEX idx_portfolio_strategist_runs_pending
    ON portfolio_strategist_runs (psr_status, psr_priority DESC, psr_created_at);
CREATE UNIQUE INDEX uq_portfolio_strategist_run_signal
    ON portfolio_strategist_runs (psr_pst_id, psr_sig_id)
    WHERE psr_sig_id IS NOT NULL;
CREATE UNIQUE INDEX uq_portfolio_strategist_run_event
    ON portfolio_strategist_runs (psr_pst_id, psr_moe_id)
    WHERE psr_moe_id IS NOT NULL;


COMMIT;
