BEGIN;

CREATE TABLE IF NOT EXISTS portfolio_strategist_attempts (
    psa_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    psa_psr_id INTEGER NOT NULL
        REFERENCES portfolio_strategist_runs(psr_id) ON DELETE CASCADE,
    psa_prm_id INTEGER REFERENCES prompts(prm_id) ON DELETE SET NULL,
    psa_attempt INTEGER NOT NULL,
    psa_status VARCHAR NOT NULL DEFAULT 'running',
    psa_model VARCHAR,
    psa_error TEXT,
    psa_created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    psa_completed_at TIMESTAMPTZ,
    CONSTRAINT chk_portfolio_strategist_attempt_status
        CHECK (psa_status IN ('running', 'succeeded', 'failed'))
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_portfolio_strategist_attempt_number
    ON portfolio_strategist_attempts (psa_psr_id, psa_attempt);

COMMIT;
