BEGIN;

CREATE TABLE IF NOT EXISTS orchestrator_cycles (
    orc_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    orc_history_key VARCHAR NOT NULL UNIQUE,
    orc_source VARCHAR NOT NULL,
    orc_started_at TIMESTAMPTZ NOT NULL,
    orc_completed_at TIMESTAMPTZ,
    orc_signal_window_start TIMESTAMPTZ NOT NULL,
    orc_prm_id INTEGER REFERENCES prompts(prm_id) ON DELETE SET NULL,
    orc_model VARCHAR,
    orc_status VARCHAR NOT NULL,
    orc_error TEXT,
    orc_snapshot JSONB NOT NULL,
    orc_raw_model_content TEXT,
    CONSTRAINT chk_orchestrator_cycle_status
        CHECK (orc_status IN ('applying', 'completed', 'failed', 'legacy'))
);
CREATE INDEX IF NOT EXISTS idx_orchestrator_cycles_started
    ON orchestrator_cycles (orc_started_at, orc_id);

CREATE TABLE IF NOT EXISTS orchestrator_decisions (
    ord_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ord_cycle_id INTEGER NOT NULL REFERENCES orchestrator_cycles(orc_id) ON DELETE CASCADE,
    ord_rsf_id INTEGER REFERENCES rss_feeds(rsf_id) ON DELETE SET NULL,
    ord_position INTEGER NOT NULL,
    ord_proposal JSONB NOT NULL,
    ord_approved BOOLEAN,
    ord_status VARCHAR NOT NULL,
    ord_rejection_reason TEXT,
    ord_error TEXT,
    ord_instruction_id VARCHAR UNIQUE,
    CONSTRAINT chk_orchestrator_decision_status
        CHECK (ord_status IN ('pending', 'rejected', 'approved', 'applied', 'failed', 'legacy_approved'))
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_orchestrator_decisions_cycle
    ON orchestrator_decisions (ord_cycle_id, ord_position);

ALTER TABLE orchestrator_analysis_jobs
    ADD COLUMN IF NOT EXISTS oaj_cycle_id INTEGER
    REFERENCES orchestrator_cycles(orc_id) ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS ix_orchestrator_analysis_jobs_oaj_cycle_id
    ON orchestrator_analysis_jobs (oaj_cycle_id);

COMMIT;
