BEGIN;

CREATE TABLE IF NOT EXISTS orchestrator_analysis_jobs (
    oaj_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    oaj_ast_id INTEGER NOT NULL REFERENCES assets(ast_id),
    oaj_result_anl_id INTEGER REFERENCES analyses(anl_id) ON DELETE SET NULL,
    oaj_question TEXT NOT NULL,
    oaj_reason TEXT NOT NULL,
    oaj_priority INTEGER NOT NULL,
    oaj_status VARCHAR NOT NULL DEFAULT 'pending',
    oaj_error TEXT,
    oaj_requested_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    oaj_started_at TIMESTAMPTZ,
    oaj_completed_at TIMESTAMPTZ,
    CONSTRAINT chk_orchestrator_analysis_job_status
        CHECK (oaj_status IN ('pending', 'running', 'succeeded', 'failed')),
    CONSTRAINT chk_orchestrator_analysis_job_priority
        CHECK (oaj_priority BETWEEN 1 AND 5)
);

CREATE INDEX IF NOT EXISTS idx_orchestrator_analysis_jobs_status_requested
    ON orchestrator_analysis_jobs (oaj_status, oaj_requested_at);

COMMIT;
