BEGIN;

CREATE TABLE IF NOT EXISTS rss_feeds (
    rsf_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rsf_name VARCHAR NOT NULL UNIQUE,
    rsf_url TEXT NOT NULL,
    rsf_source_prefix VARCHAR NOT NULL,
    rsf_poll_interval_seconds INTEGER NOT NULL DEFAULT 3600,
    rsf_status VARCHAR NOT NULL DEFAULT 'active',
    rsf_last_polled_at TIMESTAMPTZ,
    rsf_next_poll_at TIMESTAMPTZ,
    rsf_next_poll_trigger VARCHAR NOT NULL DEFAULT 'schedule',
    rsf_pending_instruction_id VARCHAR,
    rsf_last_status VARCHAR,
    rsf_last_items_processed INTEGER NOT NULL DEFAULT 0,
    rsf_last_error TEXT,
    rsf_created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    rsf_updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_rss_feed_poll_interval
        CHECK (rsf_poll_interval_seconds BETWEEN 300 AND 7200),
    CONSTRAINT chk_rss_feed_status
        CHECK (rsf_status IN ('active', 'paused')),
    CONSTRAINT chk_rss_feed_next_trigger
        CHECK (rsf_next_poll_trigger IN ('schedule', 'run_now'))
);

CREATE INDEX IF NOT EXISTS idx_rss_feeds_due
    ON rss_feeds (rsf_status, rsf_next_poll_at);

CREATE TABLE IF NOT EXISTS rss_feed_runs (
    rfr_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rfr_rsf_id INTEGER NOT NULL REFERENCES rss_feeds(rsf_id) ON DELETE CASCADE,
    rfr_trigger VARCHAR NOT NULL,
    rfr_instruction_id VARCHAR,
    rfr_status VARCHAR NOT NULL,
    rfr_started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    rfr_completed_at TIMESTAMPTZ,
    rfr_items_processed INTEGER NOT NULL DEFAULT 0,
    rfr_error TEXT,
    CONSTRAINT chk_rss_feed_run_trigger
        CHECK (rfr_trigger IN ('schedule', 'run_now')),
    CONSTRAINT chk_rss_feed_run_status
        CHECK (rfr_status IN ('running', 'succeeded', 'failed'))
);

CREATE INDEX IF NOT EXISTS idx_rss_feed_runs_feed_started
    ON rss_feed_runs (rfr_rsf_id, rfr_started_at DESC);

INSERT INTO rss_feeds
    (rsf_name, rsf_url, rsf_source_prefix, rsf_poll_interval_seconds, rsf_next_poll_at)
VALUES
    ('Investing.com', 'https://www.investing.com/rss/news_25.rss', 'rss:investing', 3600, NOW()),
    ('Google Tech News', 'https://news.google.com/rss/search?q=technology+stocks&hl=en-US&gl=US&ceid=US:en', 'rss:google', 3600, NOW()),
    ('Oil and Energy', 'https://news.google.com/rss/search?q=oil+prices+crude+oil+energy+stocks&hl=en-US&gl=US&ceid=US:en', 'rss:google', 3600, NOW()),
    ('Gold and Mining', 'https://news.google.com/rss/search?q=gold+prices+gold+mining+stocks&hl=en-US&gl=US&ceid=US:en', 'rss:google', 3600, NOW()),
    ('Mergers and Acquisitions', 'https://news.google.com/rss/search?q=mergers+acquisitions+takeovers+stocks&hl=en-US&gl=US&ceid=US:en', 'rss:google', 3600, NOW()),
    ('Federal Reserve Press Releases', 'https://www.federalreserve.gov/feeds/press_all.xml', 'rss:federal-reserve', 3600, NOW()),
    ('SEC Press Releases', 'https://www.sec.gov/news/pressreleases.rss', 'rss:sec', 3600, NOW()),
    ('SEC EDGAR 8-K Filings', 'https://www.sec.gov/cgi-bin/browse-edgar?action=getcurrent&type=8-K&owner=exclude&count=100&output=atom', 'rss:sec-edgar', 3600, NOW()),
    ('ECB Communications', 'https://www.ecb.europa.eu/rss/press.html', 'rss:ecb', 3600, NOW()),
    ('BLS Latest Releases', 'https://www.bls.gov/feed/bls_latest.rss', 'rss:bls', 3600, NOW()),
    ('EIA Today in Energy', 'https://www.eia.gov/rss/todayinenergy.xml', 'rss:eia', 3600, NOW()),
    ('Bloomberg Markets', 'https://feeds.bloomberg.com/markets/news.rss', 'rss:bloomberg', 3600, NOW()),
    ('CNBC Top News', 'https://www.cnbc.com/id/100003114/device/rss/rss.html', 'rss:cnbc', 3600, NOW()),
    ('BBC Business', 'https://feeds.bbci.co.uk/news/business/rss.xml', 'rss:bbc', 3600, NOW()),
    ('TechCrunch', 'https://techcrunch.com/feed/', 'rss:techcrunch', 3600, NOW()),
    ('CoinDesk', 'https://www.coindesk.com/arc/outboundfeeds/rss/', 'rss:coindesk', 3600, NOW())
ON CONFLICT (rsf_name) DO UPDATE SET
    rsf_url = EXCLUDED.rsf_url,
    rsf_source_prefix = EXCLUDED.rsf_source_prefix,
    rsf_updated_at = NOW();

COMMIT;
