BEGIN;

-- Past deposits changed the balance only; no historic records are invented.
CREATE TABLE IF NOT EXISTS deposits (
    dep_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dep_usr_id INTEGER NOT NULL REFERENCES users(usr_id),
    dep_admin_usr_id INTEGER NOT NULL REFERENCES users(usr_id),
    dep_amount NUMERIC(24,8) NOT NULL,
    dep_currency VARCHAR(10) NOT NULL DEFAULT 'USD',
    dep_created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_deposit_amount CHECK (dep_amount > 0),
    CONSTRAINT chk_deposit_currency CHECK (dep_currency = 'USD')
);

CREATE INDEX IF NOT EXISTS idx_deposits_user_created
    ON deposits (dep_usr_id, dep_created_at);

COMMIT;
