BEGIN;

CREATE TABLE IF NOT EXISTS portfolio_recommendations (
    prc_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prc_psr_id INTEGER NOT NULL
        REFERENCES portfolio_strategist_runs(psr_id) ON DELETE CASCADE,
    prc_prt_id INTEGER NOT NULL REFERENCES portfolios(prt_id) ON DELETE CASCADE,
    prc_ast_id INTEGER REFERENCES assets(ast_id) ON DELETE SET NULL,
    prc_sig_id INTEGER REFERENCES signals(sig_id) ON DELETE SET NULL,
    prc_kind VARCHAR NOT NULL,
    prc_asset_symbol VARCHAR,
    prc_action VARCHAR NOT NULL,
    prc_reason TEXT NOT NULL,
    prc_confidence INTEGER,
    prc_status VARCHAR NOT NULL DEFAULT 'new',
    prc_created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    prc_updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_portfolio_recommendation_kind
        CHECK (prc_kind IN ('holding_assessment', 'opportunity', 'targeted_conclusion')),
    CONSTRAINT chk_portfolio_recommendation_status
        CHECK (prc_status IN ('new', 'viewed', 'dismissed', 'acted_on')),
    CONSTRAINT chk_portfolio_recommendation_confidence
        CHECK (prc_confidence IS NULL OR prc_confidence BETWEEN 0 AND 100)
);

CREATE INDEX IF NOT EXISTS idx_portfolio_recommendations_portfolio_status
    ON portfolio_recommendations (prc_prt_id, prc_status, prc_created_at);
CREATE INDEX IF NOT EXISTS idx_portfolio_recommendations_run
    ON portfolio_recommendations (prc_psr_id);

-- Preserve useful cards from reviews completed before this normalized table
-- existed. The original full decision remains stored on the run.
INSERT INTO portfolio_recommendations (
    prc_psr_id,
    prc_prt_id,
    prc_ast_id,
    prc_kind,
    prc_asset_symbol,
    prc_action,
    prc_reason,
    prc_created_at,
    prc_updated_at
)
SELECT
    run.psr_id,
    strategist.pst_prt_id,
    asset.ast_id,
    'holding_assessment',
    UPPER(item.value->>'asset_symbol'),
    item.value->>'verdict',
    item.value->>'reason',
    COALESCE(run.psr_completed_at, run.psr_created_at),
    COALESCE(run.psr_completed_at, run.psr_created_at)
FROM portfolio_strategist_runs AS run
JOIN portfolio_strategists AS strategist ON strategist.pst_id = run.psr_pst_id
CROSS JOIN LATERAL jsonb_array_elements(
    CASE
        WHEN jsonb_typeof(run.psr_decision->'holding_assessments') = 'array'
            THEN run.psr_decision->'holding_assessments'
        ELSE '[]'::jsonb
    END
) AS item(value)
LEFT JOIN assets AS asset
    ON UPPER(asset.ast_symbol) = UPPER(item.value->>'asset_symbol')
WHERE NOT EXISTS (
    SELECT 1
    FROM portfolio_recommendations AS existing
    WHERE existing.prc_psr_id = run.psr_id
      AND existing.prc_kind = 'holding_assessment'
      AND existing.prc_asset_symbol = UPPER(item.value->>'asset_symbol')
      AND existing.prc_action = item.value->>'verdict'
      AND existing.prc_reason = item.value->>'reason'
);

INSERT INTO portfolio_recommendations (
    prc_psr_id,
    prc_prt_id,
    prc_ast_id,
    prc_sig_id,
    prc_kind,
    prc_asset_symbol,
    prc_action,
    prc_reason,
    prc_confidence,
    prc_created_at,
    prc_updated_at
)
SELECT
    run.psr_id,
    strategist.pst_prt_id,
    asset.ast_id,
    signal.sig_id,
    'opportunity',
    UPPER(item.value->>'asset_symbol'),
    'opportunity',
    item.value->>'reason',
    (item.value->>'confidence')::integer,
    COALESCE(run.psr_completed_at, run.psr_created_at),
    COALESCE(run.psr_completed_at, run.psr_created_at)
FROM portfolio_strategist_runs AS run
JOIN portfolio_strategists AS strategist ON strategist.pst_id = run.psr_pst_id
CROSS JOIN LATERAL jsonb_array_elements(
    CASE
        WHEN jsonb_typeof(run.psr_decision->'opportunities') = 'array'
            THEN run.psr_decision->'opportunities'
        ELSE '[]'::jsonb
    END
) AS item(value)
LEFT JOIN assets AS asset
    ON UPPER(asset.ast_symbol) = UPPER(item.value->>'asset_symbol')
LEFT JOIN signals AS signal
    ON signal.sig_id = CASE
        WHEN jsonb_typeof(item.value->'signal_id') = 'number'
            THEN (item.value->>'signal_id')::integer
        ELSE NULL
    END
WHERE NOT EXISTS (
    SELECT 1
    FROM portfolio_recommendations AS existing
    WHERE existing.prc_psr_id = run.psr_id
      AND existing.prc_kind = 'opportunity'
      AND existing.prc_asset_symbol = UPPER(item.value->>'asset_symbol')
      AND existing.prc_reason = item.value->>'reason'
);

INSERT INTO portfolio_recommendations (
    prc_psr_id,
    prc_prt_id,
    prc_ast_id,
    prc_sig_id,
    prc_kind,
    prc_asset_symbol,
    prc_action,
    prc_reason,
    prc_created_at,
    prc_updated_at
)
SELECT
    run.psr_id,
    strategist.pst_prt_id,
    run.psr_ast_id,
    run.psr_sig_id,
    'targeted_conclusion',
    UPPER(asset.ast_symbol),
    run.psr_decision->>'targeted_conclusion',
    run.psr_decision->>'targeted_reason',
    COALESCE(run.psr_completed_at, run.psr_created_at),
    COALESCE(run.psr_completed_at, run.psr_created_at)
FROM portfolio_strategist_runs AS run
JOIN portfolio_strategists AS strategist ON strategist.pst_id = run.psr_pst_id
LEFT JOIN assets AS asset ON asset.ast_id = run.psr_ast_id
WHERE run.psr_decision->>'targeted_conclusion' IS NOT NULL
  AND run.psr_decision->>'targeted_reason' IS NOT NULL
  AND NOT EXISTS (
      SELECT 1
      FROM portfolio_recommendations AS existing
      WHERE existing.prc_psr_id = run.psr_id
        AND existing.prc_kind = 'targeted_conclusion'
        AND existing.prc_action = run.psr_decision->>'targeted_conclusion'
        AND existing.prc_reason = run.psr_decision->>'targeted_reason'
  );

COMMIT;
